---
version: 1.0.1
name: Dokumentasi • Bawaslu Jatim
description: Dokumentasi sistem informasi Bawaslu Jatim
url: https://docs.jatimmengawasi.com
repository: https://github.com/zickkeen/bawasludocs
timezone: Asia/Jakarta
twitter:
  username: zickkeen
logo: "/img/logo-2x.png"
google_analytics_id: UA-50755011-1
google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  posts:
    permalink: "/news/:year/:month/:day/:title/"
    output: true
  tutorials:
    permalink: "/:collection/:path/"
    output: true
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
- scope:
    path: _posts
    type: posts
  values:
    layout: news_item
- scope:
    path: _tutorials
    type: tutorials
  values:
    layout: tutorials
- scope:
    path: ''
  values:
    image: "/img/jekyll-og.png"
future: true
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
feed:
  categories:
  - release
kramdown:
  syntax_highlighter_opts:
    default_lang: plaintext
sass:
  style: compressed
strict_front_matter: true
exclude:
- icomoon-selection.json
- readme.md
